# Need to explicitly force fPIC on. The LLVM release scripts also do
# this, otherwise we cannot link statically to our libc++.
set(CMAKE_POSITION_INDEPENDENT_CODE ON BOOL "")

set(CMAKE_C_FLAGS "-fno-stack-protector")
set(CMAKE_CXX_FLAGS "-fno-stack-protector")

if (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(CMAKE_C_FLAGS "${LLVM_C_FLAGS} -march=x86-64-v3")
  set(CMAKE_CXX_FLAGS "${LLVM_CXX_FLAGS} -march=x86-64-v3")
endif ()

set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_SHARED_LINKER_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_MODULE_LINKER_FLAGS ${CMAKE_CXX_FLAGS})

if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    # Force to pc-linux as opposed to unknown-linux
    set(LLVM_DEFAULT_TARGET_TRIPLE "x86_64-pc-linux-gnu" CACHE STRING  "")
endif()

set(LLVM_ENABLE_ASSERTIONS OFF CACHE BOOL "")
set(LLVM_ENABLE_BACKTRACES OFF CACHE BOOL "")
set(LLVM_ENABLE_Z3_SOLVER OFF CACHE BOOL "")
set(LLVM_ENABLE_UNWIND_TABLES OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")

if (APPLE)
    set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR OFF CACHE BOOL "")
else ()
    set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")
endif ()
set(LLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO ON CACHE BOOL "")

set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBUNWIND_ENABLE_ASSERTIONS OFF CACHE BOOL "")

set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")
set(LLVM_BUILD_EXAMPLES OFF CACHE BOOL "")
set(LLVM_BUILD_DOCS OFF CACHE BOOL "")
set(LLVM_BUILD_BENCHMARKS OFF CACHE BOOL "")
set(LLVM_INSTALL_CCTOOLS_SYMLINKS ON CACHE BOOL "")

set(CLANG_TOOL_SCAN_BUILD_BUILD OFF CACHE BOOL "")
set(CLANG_TOOL_SCAN_VIEW_BUILD OFF CACHE BOOL "")

#set(CLANG_DEFAULT_CXX_STDLIB libc++ CACHE STRING "")
set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
set(CLANG_DEFAULT_OBJCOPY llvm-objcopy CACHE STRING "")
set(CLANG_DEFAULT_UNWINDLIB libunwind CACHE STRING "")
set(CLANG_PLUGIN_SUPPORT OFF CACHE BOOL "")
set(CLANG_SPAWN_CC1 OFF CACHE BOOL "")

set(LLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO ON CACHE BOOL "")
