set (IS_LINUX OFF)
set (IS_MAC OFF)
set (IS_WINDOWS OFF)
if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set (IS_LINUX ON)
elseif (APPLE)
    set (IS_MAC ON)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set (IS_WINDOWS ON)
endif()
